name: yaml format

on:
  push:
    paths: strings/strings/*
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prettify code
      uses: creyD/prettier_action@v4.1.1
      with:
        prettier_options: --write **/*.{yml,md}
        commit_message: "yaml format"
        
